name: Auto-Sync

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: 0 20 * * *

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: CheckOut
      uses: actions/checkout@v2

    - name: 配置git信息
      run: |
        mkdir -p ~/.ssh/
        echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        git config --global user.name '${{ secrets.USER_NAME }}'
        git config --global user.email '$${{ secrets.USER_EMAIL }}'

    - name: 同步中...
      run: |
        git clone git@github.com:${{ secrets.USER_NAME }}/Auto-Sync.git
        cp Auto-Sync/forks.txt forks.txt
        for line in $(cat forks.txt)
        do
        jobs=$(echo $(sed -n 1p forks.txt))
        rep=$(echo ${jobs#*/})
        upc=$(echo $(curl -s https://github.com/$jobs/commits/master | grep -m1 -E "https://github.com/$jobs/commit/\w{40}" | grep -o -E "\w{40}"))
        myc=$(echo $(curl -s https://github.com/${{ secrets.USER_NAME }}/$rep/commits/master | grep -m1 -E "https://github.com/${{ secrets.USER_NAME }}/$rep/commit/\w{40}" | grep -o -E "\w{40}"))
        if [ $upc != $myc ]; then
        echo "***********************************"
        echo "$rep 开始同步"
        echo "***********************************"
        git clone git@github.com:${{ secrets.USER_NAME }}/$rep dir
        cd dir
        git remote add upstream git@github.com:$jobs
        git pull upstream master
        git add .
        git commit -m "Sync Upstream"
        git push
        cd ..
        rm -rf dir
        echo "***********************************"
        echo "$rep 同步完成"
        echo "***********************************"
        else
        echo "***********************************"
        echo "$rep 暂无更新" 
        echo "***********************************"
        fi
        sed -i '1d' forks.txt
        done
        echo "***********************************"
        echo "所有fork项目都同步完成!"
        echo "***********************************"
